#%Module######################################################################
##                                             Andre.VanderWesthuysen@NOAA.gov
##                                                    IMSG @ NOAA/NWS/NCEP/EMC
## GLWU v1.1.0
##_____________________________________________________
proc ModulesHelp { } {
puts stderr "Set environment for the Great Lakes GLWU"
puts stderr "This module initializes the environment "
puts stderr "for the WCOSS2 Cray implementation of GLWU\n"
}
module-whatis " GLWU whatis description"

set ver v1.1.0

set sys [uname sysname]

# Loading Intel Compiler Suite
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load intel/19.1.3.304
# used for multiwavegrib2
module load jasper/2.0.25
module load libpng/1.6.37
module load zlib/1.2.11
module load g2/3.4.5
# used for multiwavegrib1 and grib2
module load w3nco/2.4.1
module load bacio/2.4.1
