
############################################
### JWAVE_GLWU_MIC_PREP: Great Lakes Wave Sys ###
###      LSF card for development        ###
############################################
#
# LSF options
#
#PBS -A GLWU-DEV
#PBS -N JWAVE_GLWU_PREP
#PBS -q dev
#PBS -l walltime=00:20:00
#PBS -l select=1:ncpus=120:mem=2700MB
#PBS -l place=excl
#PBS -V
#PBS -j oe
#PBS -o JWAVE_GLWU_PREP.out
#PBS -e JWAVE_GLWU_PREP.out

cd $PBS_O_WORKDIR

# Setup and load modules 
module load envvar/1.0
module load prod_envir/2.0.5
module load prod_util/2.0.8
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load intel/19.1.3.304
module load cray-mpich/8.1.7
module load cray-pals/1.0.12
module load cfp/2.0.4
module load wgrib2/2.0.8_mpi
module load hdf5/1.10.6
module load iobuf/2.0.10
module list

# Set LSF variables
export MP_EAGER_LIMIT=165536
export MP_COREFILE_FORMAT=core.txt
export MP_EUIDEVELOP=min
export MP_MPILIB=mpich2

export MP_LABELIO=yes
export MP_SINGLE_THREAD=yes
export MP_USE_BULK_XFER=yes
export MPICH_ALLTOALL_THROTTLE=0

export MP_TASK_AFFINITY=cpu
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us

ulimit -s unlimited

export IOBUF_PARAMS='*.dat:count=4:size=32M:prefetch=1:preflush=1'

# Set global variables
export modID=glwu
export MODID=GLWU
export RUN=$modID

runuser=$USER
NWROOT=/lfs/h2/emc/couple/noscrub/${runuser}      # root of file system

# Set paths to home etc
export NET=wave
export HOMEwave=${HOMEwave:-/lfs/h2/emc/couple/noscrub/${runuser}/${sysver}}

# Check HOST file for where to run
. ./HOST_${modID}

# Set pref to point to matching CRAY machines
pref=$( echo $COMROOTp1 | cut -c7 )
export WCOSS_SYSTEM=$( echo $COMROOTp1 | cut -c7 )d1
export WCOSS_SYSTEM_COM=$( echo $COMROOTp1 | cut -c7-9)


# Lines below for retrospective testing using data in noscrub
# export DCOM=/gpfs/hps3/emc/marine/noscrub/${runuser}/GLWU_Q1FY15/DCOM
# export INCOM=/gpfs/hps3/emc/marine/noscrub/${runuser}/GLWU_Q1FY15

export job=JWAVE_GLWU_PREP
export SMSBIN=/gpfs/${pref}p1/emc/globaldump/sms_fake

 #Set Version numbers
if [ -f "$HOMEwave/versions/wave_glwu.ver" ]
then
  source $HOMEwave/versions/wave_glwu.ver
else
  echo '##############################################'
  echo '### ERROR !! : COULD NOT FIND VERSION CARD ###'
  echo "$HOMEwave/version/wave_glwu.ver"
  echo '##############################################'
  exit 1
fi

# Set PDY and cycle here
export COMDATE=`pwd`

echo $COMDATE
ls $COMDATE

if [ -f $COMDATE/PDY_${modID} ]
then
   source $COMDATE/PDY_${modID}
else
  echo '##################################################'
  echo '### ERROR !! : COULD NOT SET THE PDY AND CYCLE ###'
  echo '##################################################'
  exit 1
fi
PDY_file=$PDY
cyc_file=$cyc
# Set j-job parameters (extracted from j-job for DEV by new NCO standards)
# the stmp file system is hugely slow
export DATA=/lfs/h2/emc/ptmp/${runuser}/${GLWUdir}/${envir}/${job}
#export DATA=/gpfs/hps3/ptmp/wavepa/${envir}/${job}
#export DATA=/gpfs/hps3/emc/marine/noscrub/${runuser}/tmp/${envir}/${job}
rm -rf $DATA
mkdir -p $DATA
export jlogfile=/dev/null
export SENDECF=NO 
export SENDDBN=NO
export SENDCOM=YES 
#
# Delete DEVCOMIN variable once code is ready to read winds
#  and ice from noscrub
if  [ "$RetroRun" = "YES" ]
then
   export DCOMIN=/gpfs/hps3/emc/marine/noscrub/${runuser}/GLWUInput
else
   DCOMROOT=/lfs/h2/emc/couple/noscrub/Andre.VanderWesthuysen/GLWU/dcom
   export DCOMIN=${DCOMROOT}/prod
fi

# Location of WW3 code
#export CODEwave=${CODEwave:-/lfs/h2/emc/couple/noscrub/${runuser}/${NET}_code.${wave_code_ver}/${wave_code_pkg}}
export CODEwave=${CODEwave:-/lfs/h2/emc/couple/noscrub/${runuser}/${NET}_${modID}.${wave_glwu_ver}}

# Set COM paths
export COMINwave=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}
export COMIN=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}/${RUN}.${PDY}

export COMOUTwave=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}
export COMOUT=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}/${RUN}.${PDY}
export COMINOUT=$COMOUT

export COMROOT=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}

#There was a change for the wind name in the ndfd files this happenned at 20181030_15
#So the variable name must be change in ~fix/multiwaveprnc.ndfd
# FROM: UGRD_surface VGRD_surface   --->   UGRD_10maboveground VGRD_10maboveground
#Looking for the actual PDY and cycle
export PDYcyc_changed=2018103014

cyc_now=$(date -u +%H)
export utilscript=${UTILROOT}/ush
sh $utilscript/setpdy.sh
mv PDY PDY.TODAY
. ./PDY.TODAY
PDYcyc_file="${PDY_file}${cyc_file}"
echo "COMPARING $PDYcyc_file >= $PDYcyc_changed ?"

#if [ "$PDYcyc_file" -gt "$PDYcyc_changed" ] 
#then 
#  echo "THIS IS A RUN AFTER 20181030_14"
#  # IF the tmpl file is not ready for REAL TIME then edited
#  sed -i 's/ UGRD_surface VGRD_surface/ UGRD_10maboveground VGRD_10maboveground/g' $HOMEwave/fix/multiwaveprnc.ndfd_glwu.tmpl
#else
#  echo "THIS IS A RETROSPECTIVE OR HINDCAST RUN"
#  # EDIT the   fix/multiwaveprnc.ndfd_glwu.tmpl
# sed -i 's/ UGRD_10maboveground VGRD_10maboveground/ UGRD_surface VGRD_surface/g' $HOMEwave/fix/multiwaveprnc.ndfd_glwu.tmpl
#fi

export PDY=$PDY_file
export cyc=$cyc_file

# Choose to keep temporary directory
export KEEPDATA='YES'

# Execute the actual J job
############################################################################
${NWROOT}/wave_${modID}.${wave_glwu_ver}/jobs/JWAVE_${MODID}_PREP
############################################################################
