############################################
### JWAVE_GLWU_FORECAST: Great Lakes Wave Sys ###
###      LSF card for development        ###
############################################
#
# LSF options
#
#PBS -A GLWU-DEV
#PBS -N JWAVE_GLWU_FORECAST
#PBS -q dev
#PBS -l walltime=01:00:00
##PBS -l select=6:ncpus=128:mem=150GB
#PBS -l select=24:ncpus=32
#PBS -l place=excl
#PBS -V
#PBS -j oe
#PBS -o JWAVE_GLWU_FORECAST.out
#PBS -e JWAVE_GLWU_FORECAST.out

cd $PBS_O_WORKDIR

# Setup the modules
module load envvar/1.0
module load prod_envir/2.0.5
module load prod_util/2.0.8
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load intel/19.1.3.304
module load cray-mpich/8.1.7
module load cray-pals/1.0.12
module load hdf5/1.10.6
module load netcdf/4.7.4
module load jasper/2.0.25
module load libpng/1.6.37
module load zlib/1.2.11
module load g2/3.4.5
module load w3nco/2.4.1
module load bacio/2.4.1
module load iobuf/2.0.10
module list

# Set LSF variables
export KMP_AFFINITY=disabled
# specify X threads if using openmp
export OMP_NUM_THREADS=1

ulimit -s unlimited

export IOBUF_PARAMS='*:count=4:size=32M:prefetch=1:preflush=1'

# Set global variables
export modID=glwu
export MODID=GLWU
export RUN=$modID

runuser=$USER
NWROOT=/lfs/h2/emc/couple/noscrub/${runuser}      # root of file system

# envir now set by version card

# Check HOST file for where to run
. ./HOST_${modID}

pref=$( echo $COMROOTp1 | cut -c7 )
export WCOSS_SYSTEM=$( echo $COMROOTp1 | cut -c7 )d1
export WCOSS_SYSTEM_COM=$( echo $COMROOTp1 | cut -c7-9)

# Set pref to point to matching CRAY machines
#if [ "${pref}" == "l" ]
#then
#  pref='t'
#else
# pref='g'
#fi

# Lines below for retrospective testing using data in noscrub
# export DCOM=/gpfs/hps3/emc/marine/noscrub/${runuser}/GLWU_Q1FY15/DCOM
# export INCOM=/gpfs/hps3/emc/marine/noscrub/${runuser}/GLWU_Q1FY15

export job=JWAVE_GLWU_FORECAST
export SMSBIN=/gpfs/${pref}p1/emc/globaldump/sms_fake

 #Set Version numbers
version_file=$NWROOT/${sysver}/versions/wave_glwu.ver      # file with version info
if [ -f $version_file ]
then
  source $version_file
else
  echo '##############################################'
  echo '### ERROR !! : COULD NOT FIND VERSION CARD ###'
  echo '##############################################'
  exit 1
fi

# Set PDY and cycle here
export COMDATE=`pwd`

echo $COMDATE
ls $COMDATE

if [ -f $COMDATE/PDY_${modID} ]
then
   source $COMDATE/PDY_${modID}
else
  echo '##################################################'
  echo '### ERROR !! : COULD NOT SET THE PDY AND CYCLE ###'
  echo '##################################################'
  exit 1
fi

# Set j-job parameters (extracted from j-job for DEV by new NCO standards)
# the stmp file system is hugely slow
export DATA=/lfs/h2/emc/ptmp/${runuser}/${GLWUdir}/${envir}/${job}
#export DATA=/gpfs/hps3/ptmp/wavepa/${envir}/${job}
#export DATA=/gpfs/hps3/emc/marine/noscrub/${runuser}/tmp/${envir}/${job}
rm -rf $DATA
mkdir -p $DATA
export jlogfile=/dev/null
export SENDECF=NO 
export SENDDBN=NO
export SENDCOM=YES 

# Set paths to home etc
export NET=wave
#export CODEwave=${CODEwave:-/lfs/h2/emc/couple/noscrub/${runuser}/${NET}_code.${wave_code_ver}/${wave_code_pkg}}
export CODEwave=${CODEwave:-/lfs/h2/emc/couple/noscrub/${runuser}/${NET}_${modID}.${wave_glwu_ver}}
export HOMEwave=${HOMEwave:-/lfs/h2/emc/couple/noscrub/${runuser}/${NET}_${modID}.${wave_glwu_ver}}

# Set COM paths
export COMINwave=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}
export COMIN=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}/${RUN}.${PDY}

export COMOUTwave=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}
export COMOUT=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}/${RUN}.${PDY}
export COMINOUT=$COMOUT

export COMROOT=/lfs/h2/emc/couple/noscrub/${runuser}/${GLWUdir}/COM_${envir}
#export DCOMROOT=/gpfs/${pref}p1/nco/GLWU_Danger_Seas/dcom

# Choose to keep temporary directory
export KEEPDATA='YES'

# Set aprun options consistent with resource allocation
#export mpicmd='mpiexec -n 768 -ppn 128'
export mpicmd='mpiexec -n 768 -ppn 32 --depth 4 --cpu-bind depth'

# Execute the actual J job
############################################################################
${NWROOT}/wave_${modID}.${wave_glwu_ver}/jobs/JWAVE_${MODID}_FORECAST
############################################################################
