
############################################
### JWAVE_GLWU_MIC_PREP: Great Lakes Wave Sys ###
###      LSF card for development        ###
############################################
#
# LSF options
#
#BSUB -M 2700
##BSUB -M 100
#BSUB -P GLW-T2O
#BSUB -J JWAVE_GLWU_PREP
#BSUB -extsched 'CRAYLINUX[]' -R '1*{select[craylinux && !vnode]} +120*{select[craylinux && vnode]span[ptile=24] cu[type=cabinet]}'
#BSUB -oo JWAVE_GLWU_PREP.out
#BSUB -eo JWAVE_GLWU_PREP.out 
#BSUB -W 00:20
#BSUB -q "dev"
##BSUB -q "debug"
#BSUB -cwd /gpfs/hps3/emc/marine/noscrub/Andre.VanderWesthuysen/wave_glwu.v1.0.3/dev/lsf_scripts

# Setup and load modules 
source $MODULESHOME/etc/modules.sh
module load PrgEnv-intel
module load prod_util
module load prod_envir

module load cfp-intel-sandybridge/1.1.0
module load grib_util/1.0.3
module load iobuf/2.0.5

# Set LSF variables
export MP_EAGER_LIMIT=165536
export MP_COREFILE_FORMAT=core.txt
export MP_EUIDEVELOP=min
export MP_MPILIB=mpich2

export MP_LABELIO=yes
export MP_SINGLE_THREAD=yes
export MP_USE_BULK_XFER=yes
export MPICH_ALLTOALL_THROTTLE=0

export MP_TASK_AFFINITY=cpu
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us

ulimit -s unlimited

export IOBUF_PARAMS='*.dat:count=4:size=32M:prefetch=1:preflush=1'

# Set global variables
export modID=glwu
export MODID=GLWU
export RUN=$modID

runuser=$USER
NWROOT=/gpfs/hps3/emc/marine/noscrub/${runuser}      # root of file system

# Set paths to home etc
export NET=wave
export HOMEwave=${HOMEwave:-/gpfs/hps3/emc/marine/noscrub/${runuser}/wave_glwu.v1.0.3}

# Check HOST file for where to run
. ./HOST_${modID}

# Set pref to point to matching CRAY machines
module load prod_envir
pref=$( echo $COMROOTp1 | cut -c7 )
export WCOSS_SYSTEM=$( echo $COMROOTp1 | cut -c7 )d1
export WCOSS_SYSTEM_COM=$( echo $COMROOTp1 | cut -c7-9)


# Lines below for retrospective testing using data in noscrub
# export DCOM=/gpfs/hps3/emc/marine/noscrub/${runuser}/GLWU_Q1FY15/DCOM
# export INCOM=/gpfs/hps3/emc/marine/noscrub/${runuser}/GLWU_Q1FY15

export job=JWAVE_GLWU_PREP
export SMSBIN=/gpfs/${pref}p1/emc/globaldump/sms_fake

 #Set Version numbers
if [ -f "$HOMEwave/versions/wave_glwu.ver" ]
then
  source $HOMEwave/versions/wave_glwu.ver
else
  echo '##############################################'
  echo '### ERROR !! : COULD NOT FIND VERSION CARD ###'
  echo "$HOMEwave/version/wave_glwu.ver"
  echo '##############################################'
  exit 1
fi

# Set PDY and cycle here
export COMDATE=`pwd`

echo $COMDATE
ls $COMDATE

if [ -f $COMDATE/PDY_${modID} ]
then
   source $COMDATE/PDY_${modID}
else
  echo '##################################################'
  echo '### ERROR !! : COULD NOT SET THE PDY AND CYCLE ###'
  echo '##################################################'
  exit 1
fi
PDY_file=$PDY
cyc_file=$cyc
# Set j-job parameters (extracted from j-job for DEV by new NCO standards)
# the stmp file system is hugely slow
export DATA=/gpfs/hps3/stmp/${runuser}/${GLWUdir}/${envir}/${job}
#export DATA=/gpfs/hps3/ptmp/wavepa/${envir}/${job}
#export DATA=/gpfs/hps3/emc/marine/noscrub/${runuser}/tmp/${envir}/${job}
rm -rf $DATA
mkdir -p $DATA
export jlogfile=/dev/null
export SENDECF=NO 
export SENDDBN=NO
export SENDCOM=YES 
#
# Delete DEVCOMIN variable once code is ready to read winds
#  and ice from noscrub
#if  [ "$RetroRun" = "YES" ]
#then
#   export DCOMIN=/gpfs/hps3/emc/marine/noscrub/${runuser}/GLWUInput
#else
#   export DCOMIN=${DCOMROOT}/prod
#fi
#
# Location of WW3 code
export CODEwave=${CODEwave:-/gpfs/hps3/emc/marine/noscrub/${runuser}/${NET}_code.${wave_code_ver}/${wave_code_pkg}}
# Set COM paths
export COMINwave=/gpfs/hps3/emc/marine/noscrub/${runuser}/${GLWUdir}/COM_${envir}
export COMIN=/gpfs/hps3/emc/marine/noscrub/${runuser}/${GLWUdir}/COM_${envir}/${RUN}.${PDY}

export COMOUTwave=/gpfs/hps3/emc/marine/noscrub/${runuser}/${GLWUdir}/COM_${envir}
export COMOUT=/gpfs/hps3/emc/marine/noscrub/${runuser}/${GLWUdir}/COM_${envir}/${RUN}.${PDY}
export COMINOUT=$COMOUT

export COMROOT=/gpfs/hps3/emc/marine/noscrub/${runuser}/${GLWUdir}/COM_${envir}
#export DCOMROOT=/gpfs/dell1/p1/nco/GLWU_Danger_Seas/dcom

#There was a change for the wind name in the ndfd files this happenned at 20181030_15
#So the variable name must be change in ~fix/multiwaveprnc.ndfd
# FROM: UGRD_surface VGRD_surface   --->   UGRD_10maboveground VGRD_10maboveground
#Looking for the actual PDY and cycle
export PDYcyc_changed=2018103014

cyc_now=$(date -u +%H)
export utilscript=${UTILROOT}/ush
sh $utilscript/setpdy.sh
mv PDY PDY.TODAY
. ./PDY.TODAY
PDYcyc_file="${PDY_file}${cyc_file}"
echo "COMPARING $PDYcyc_file >= $PDYcyc_changed ?"

export HOMEwave=${HOMEwave:-/gpfs/hps3/emc/marine/noscrub/${runuser}/${NET}_${modID}.${wave_glwu_ver}}
#if [ "$PDYcyc_file" -gt "$PDYcyc_changed" ] 
#then 
#  echo "THIS IS A RUN AFTER 20181030_14"
#  # IF the tmpl file is not ready for REAL TIME then edited
#  sed -i 's/ UGRD_surface VGRD_surface/ UGRD_10maboveground VGRD_10maboveground/g' $HOMEwave/fix/multiwaveprnc.ndfd_glwu.tmpl
#else
#  echo "THIS IS A RETROSPECTIVE OR HINDCAST RUN"
#  # EDIT the   fix/multiwaveprnc.ndfd_glwu.tmpl
# sed -i 's/ UGRD_10maboveground VGRD_10maboveground/ UGRD_surface VGRD_surface/g' $HOMEwave/fix/multiwaveprnc.ndfd_glwu.tmpl
#fi

export PDY=$PDY_file
export cyc=$cyc_file

# Choose to keep temporary directory
export KEEPDATA='YES'

# Execute the actual J job
############################################################################
${NWROOT}/wave_${modID}.${wave_glwu_ver}/jobs/JWAVE_${MODID}_PREP
############################################################################
