#!/bin/bash

date

set -xa

export PS4='$SECONDS + '
 
# PATH for working directory
export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p $DATA
cd $DATA

# Set cycle parameters
export cycle=${cycle:-t${cyc}z}
setpdy.sh   #prod_util module needs to be loaded upstream of this
. PDY
 
# NCO alerts and outputs 
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDCOM=${SENDCOM:-YES}

# Set runID 
export runID=glwu
export modID=glwu

export NET=wave
export RUN=glwu

# Path to HOME Directory
export HOMEwave=${HOMEwave:-${NWROOT}/${NET}_${modID}.${wave_glwu_ver}}
export CODEwave=${CODEwave:-${NWROOT}/${NET}_code.${wave_code_ver}/${code_pkg}}

export EXECwave=${EXECwave:-${HOMEwave}/exec}
export FIXwave=${FIXwave:-${HOMEwave}/fix}
export PARMwave=${PARMwave:-${HOMEwave}/parm}
export USHwave=${USHwave:-${HOMEwave}/ush}
export EXECcode=${EXECcode:-${CODEwave}/exec}

# Set COM Paths
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINwave=${COMINwave:-${COMROOT}/${NET}/${envir}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUTwave=${COMOUTwave:-${COMROOT}/${NET}/${envir}}
export COMINOUT=${COMINOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}

if [ "$SENDCOM" = YES ]; then
  mkdir -p $COMOUT
fi

export wavelog=${COMOUTwave}/wave.log

env

####################################################
# Checking Daylight Savings  
# per the requirements from TIN 08-62:
#
# THERE WILL BE FOUR DISTRIBUTIONS A DAY CORRESPONDING TO THE 
# 0200...0800...1400...2000 UTC MODEL RUNS EXCEPT DURING DAYLIGHT 
# SAVINGS TIME /0100...0700...1300...1900 UTC/. NOAAPORT DELIVERY  
# WILL BE APPROXIMATELY 30 MINUTES AFTER THE MODEL RUN.
# 
#  CYC    03Z      09Z      15Z      21Z
#  EST    02:05Z   08:05Z   14:05Z   20:05Z
#  DST    01:05Z   07:05Z   13:05Z   19:05Z
#  local  21:05PM  03:05AM  09:05AM  03:05PM
####################################################
export DST_check=${DST_check:-/nw${envir}/util/ush/DST_check.pl}
export DST=`perl $DST_check`;
current_cyc=`$utilexec/ndate | cut -c 9-10`;
delta=`expr $cyc - $current_cyc`;
 
echo "The Daylight Savings status is " $DST " cyc=" $cyc "current_cyc=" $current_cyc "delta=" $delta;

if [ $DST == 'EST' ] || [ $DST == 'DST' ]; then 
  if [ $DST == 'EST' ] && [ $delta -gt 1 ]; then    # Daylight Savings is not activated (OFF)  
    echo "The wave_glwn job run too early ...";
    echo " Wait for next cycle, exiting .... ";
  elif [ $DST == 'DST' ] && [ $delta -gt 2 ]; then  # Daylight Savings is activated (ON)
    echo "The wave_glwn job run too early ...";
    echo " Wait for next cycle, exiting .... ";
  else
    echo "It's time to run wave_glwn jobs ..."
    ecflow_client --event $DST
    sleep 30
  fi
else
  echo "The Daylight Savings status is wrong ", $DST, " , Please check !!!! ";
  export err=2; err_chk;
fi

###################################
# Remove temp directories
###################################

if [ "$KEEPDATA" != YES ]; then
  rm -rf $DATA
fi

date
