#!/bin/sh

set -xa
# ###################################
# SET WAVE SHELL PROCESSING VARIABLES
# ###################################
#
# obtain unique process id (pid) and make temp directory
#
export PS4='$SECONDS + '
date

export pid=$$

if [ "${envir}" = 'prod' ];
then
   export DATA=/tmpnwprd1/$job.${pid}
else
   export DATA=/tmpnwprd2/$job.${pid}
fi

mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z
export NET=wave
export RUN=glwu

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}
export DBNLOG=${DBNLOG:-YES}
export DBNtag=${DBNtag:="_PARA"}  # '=' used instead of '-' to ensure to use the non-prod alert type for non-prod jobs
export PCOM=${PCOM:-/pcom/${envir}/${NET}}

####################################
# Path to HOME Directory
####################################
export HOMEwave=${HOMEwave:-/nw${envir}/${NET}_${modID}.${model_ver}}
export CODEwave=${CODEwave:-/nw${envir}/${NET}_code.${code_ver}/${code_pkg}}

export EXECwave=${EXECwave:-${HOMEwave}/exec}
export FIXwave=${FIXwave:-${HOMEwave}/fix}
export PARMwave=${PARMwave:-${HOMEwave}/parm}
export USHwave=${USHwave:-${HOMEwave}/ush}
export EXECcode=${EXECcode:-${CODEwave}/exec}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

#export MP_PULSE=0
#export MP_TIMEOUT=9000
 
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN_GB2=${SENDDBN_GB2:-YES}
export GET_IOPROFILE=${GET_IOPROFILE:-NO}
export DBNtag=${DBNtag:-""}

export modID=glwu               # model ID for file names

# Run setpdy and initialize PDY variables
sh $UTILROOT/setpdy.sh
. PDY

export com=${com:-/com/${NET}/${envir}}
export COMIN=${COMIN:-/com/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-/com/${NET}/${envir}/${RUN}.${PDY}}
export PCOM=${PCOM:-/pcom/${NET}}

mkdir -p $COMOUT
mkdir -p $PCOM
export wavelog=${com}/wave.log
 
env

########################################################
# Execute the script.
if [ $GET_IOPROFILE = YES ]; then
   /usrx/local/mio/tools/bin/miostats -X0 \
   ${HOMEwave}/scripts/exwave_glwu_pgen.sh.ecf
else
   ${HOMEwave}/scripts/exwave_glwu_pgen.sh.ecf
fi
########################################################

##################################################
# save the profiling data captured from miostats
##################################################
if [ $GET_IOPROFILE = YES ]; then
    . /com/miostats/.set_IOprofile
fi

cd /tmpnwprd1
    [ -z $keepwrkdir ] &&  rm -rf ${DATA}

date
