#!/bin/bash

date

set -xa

export PS4='$SECONDS + '
 
# PATH for working directory
export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p $DATA
cd $DATA

# Set cycle parameters
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

# NCO alerts and outputs 
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDCOM=${SENDCOM:-YES}

# Set runID (Until modID becomes glwn and glw is dumped) 
export runID=glwu
export modID=glwu

export NET=wave
export RUN=glwu
export IceHighResol=HIGH   # For Operations
export RetroRunOper=NOT   # For Operations
export IceResol=${IceResol:-${IceHighResol}}
export RetroRun=${RetroRun:-${RetroRunOper}}


# Path to HOME Directory
export HOMEwave=${HOMEwave:-${NWROOT}/${NET}_${modID}.${wave_glwu_ver}}
export CODEwave=${CODEwave:-${NWROOT}/${NET}_code.${wave_code_ver}/${wave_code_pkg}}

export EXECwave=${EXECwave:-${HOMEwave}/exec}
export FIXwave=${FIXwave:-${HOMEwave}/fix}
export PARMwave=${PARMwave:-${HOMEwave}/parm}
export USHwave=${USHwave:-${HOMEwave}/ush}
export EXECcode=${EXECcode:-${CODEwave}/exec}
#===================================
export PDYcyc_changed=2018103014
PDYcyc_file="${PDY}${cyc}"
if [ "$PDYcyc_file" -gt "$PDYcyc_changed" ] 
then 
  echo "THIS IS A RUN AFTER 20181030_14"
  # IF the tmpl file is not ready for REAL TIME then edited
  sed -i 's/ UGRD_surface VGRD_surface/ UGRD_10maboveground VGRD_10maboveground/g' $HOMEwave/fix/multiwaveprnc.ndfd_glwu.tmpl
  cat $HOMEwave/fix/multiwaveprnc.ndfd_glwu.tmpl
else
  echo "THIS IS A RETROSPECTIVE OR HINDCAST RUN"
  # EDIT the   fix/multiwaveprnc.ndfd_glwu.tmpl
 sed -i 's/ UGRD_10maboveground VGRD_10maboveground/ UGRD_surface VGRD_surface/g' $HOMEwave/fix/multiwaveprnc.ndfd_glwu.tmpl
fi

#===================================

# Location of NDFD input files
export DCOMIN=${DCOMIN:-${DCOMROOT}/us007003} # serves ice and ndfd data
## in prep.lsf DCOMROOT=/gpfs/${pref}p1/nco/ops/dcom

# Set COM Paths
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINwave=${COMINwave:-${COMROOT}/${NET}/${envir}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUTwave=${COMOUTwave:-${COMROOT}/${NET}/${envir}}
export COMINOUT=${COMINOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}

if [ "$SENDCOM" = YES ]; then
  mkdir -p $COMOUT
fi

export wavelog=${COMOUTwave}/wave.log

env

startmsg

# Execute the Script  
${HOMEwave}/scripts/exwave_${modID}_prep.sh.ecf
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
 
if [ "$KEEPDATA" != YES ]; then
  rm -rf $DATA
fi

date
