#!/bin/bash

date

set -xa

export PS4='$SECONDS + '
 
# PATH for working directory
export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p $DATA
cd $DATA

# Set cycle parameters
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

# NCO alerts and outputs 
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDCOM=${SENDCOM:-YES}

# Set runID (Until modID becomes glwn and glw is dumped) 
export runID=glwu
export modID=glwu

export NET=wave
export RUN=glwu

# Path to HOME Directory
export HOMEwave=${HOMEwave:-${NWROOT}/${NET}_${modID}.${wave_glwu_ver}}
export CODEwave=${CODEwave:-${NWROOT}/${NET}_code.${wave_code_ver}/${wave_code_pkg}}

export EXECwave=${EXECwave:-${HOMEwave}/exec}
export FIXwave=${FIXwave:-${HOMEwave}/fix}
export PARMwave=${PARMwave:-${HOMEwave}/parm}
export USHwave=${USHwave:-${HOMEwave}/ush}
export EXECcode=${EXECcode:-${CODEwave}/exec}

# Set COM Paths
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINwave=${COMINwave:-${COMROOT}/${NET}/${envir}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUTwave=${COMOUTwave:-${COMROOT}/${NET}/${envir}}

if [ "$SENDCOM" = YES ]; then
  mkdir -p $COMOUT 
fi

export wavelog=${COMOUTwave}/wave.log

env

# Execute the Script  
${HOMEwave}/scripts/exwave_${modID}_post.sh.ecf
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
 
if [ "$KEEPDATA" != YES ]; then
  rm -rf $DATA
fi

date
